services:
  - type: web
    name: three-bookworms
    runtime: node
    plan: free
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: SUPABASE_STATE_ID
        value: main
